/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.dl.cleaner.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the WcReferencedFile service. Represents a row in the &quot;DlCleaner_WcReferencedFile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.dl.cleaner.model.impl.WcReferencedFileModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.dl.cleaner.model.impl.WcReferencedFileImpl}.
 * </p>
 *
 * @author guywandji
 * @see WcReferencedFile
 * @see com.liferay.dl.cleaner.model.impl.WcReferencedFileImpl
 * @see com.liferay.dl.cleaner.model.impl.WcReferencedFileModelImpl
 * @generated
 */
public interface WcReferencedFileModel extends BaseModel<WcReferencedFile>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a wc referenced file model instance should use the {@link WcReferencedFile} interface instead.
	 */

	/**
	 * Returns the primary key of this wc referenced file.
	 *
	 * @return the primary key of this wc referenced file
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this wc referenced file.
	 *
	 * @param primaryKey the primary key of this wc referenced file
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the wc refenced file ID of this wc referenced file.
	 *
	 * @return the wc refenced file ID of this wc referenced file
	 */
	public long getWcRefencedFileId();

	/**
	 * Sets the wc refenced file ID of this wc referenced file.
	 *
	 * @param wcRefencedFileId the wc refenced file ID of this wc referenced file
	 */
	public void setWcRefencedFileId(long wcRefencedFileId);

	/**
	 * Returns the group ID of this wc referenced file.
	 *
	 * @return the group ID of this wc referenced file
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this wc referenced file.
	 *
	 * @param groupId the group ID of this wc referenced file
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this wc referenced file.
	 *
	 * @return the company ID of this wc referenced file
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this wc referenced file.
	 *
	 * @param companyId the company ID of this wc referenced file
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this wc referenced file.
	 *
	 * @return the user ID of this wc referenced file
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this wc referenced file.
	 *
	 * @param userId the user ID of this wc referenced file
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this wc referenced file.
	 *
	 * @return the user uuid of this wc referenced file
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this wc referenced file.
	 *
	 * @param userUuid the user uuid of this wc referenced file
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this wc referenced file.
	 *
	 * @return the user name of this wc referenced file
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this wc referenced file.
	 *
	 * @param userName the user name of this wc referenced file
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this wc referenced file.
	 *
	 * @return the create date of this wc referenced file
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this wc referenced file.
	 *
	 * @param createDate the create date of this wc referenced file
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this wc referenced file.
	 *
	 * @return the modified date of this wc referenced file
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this wc referenced file.
	 *
	 * @param modifiedDate the modified date of this wc referenced file
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the wc url title of this wc referenced file.
	 *
	 * @return the wc url title of this wc referenced file
	 */
	@AutoEscape
	public String getWcUrlTitle();

	/**
	 * Sets the wc url title of this wc referenced file.
	 *
	 * @param wcUrlTitle the wc url title of this wc referenced file
	 */
	public void setWcUrlTitle(String wcUrlTitle);

	/**
	 * Returns the dl file uu ID of this wc referenced file.
	 *
	 * @return the dl file uu ID of this wc referenced file
	 */
	@AutoEscape
	public String getDlFileUuId();

	/**
	 * Sets the dl file uu ID of this wc referenced file.
	 *
	 * @param dlFileUuId the dl file uu ID of this wc referenced file
	 */
	public void setDlFileUuId(String dlFileUuId);

	/**
	 * Returns the orphan of this wc referenced file.
	 *
	 * @return the orphan of this wc referenced file
	 */
	public boolean getOrphan();

	/**
	 * Returns <code>true</code> if this wc referenced file is orphan.
	 *
	 * @return <code>true</code> if this wc referenced file is orphan; <code>false</code> otherwise
	 */
	public boolean isOrphan();

	/**
	 * Sets whether this wc referenced file is orphan.
	 *
	 * @param orphan the orphan of this wc referenced file
	 */
	public void setOrphan(boolean orphan);

	/**
	 * Returns the type of this wc referenced file.
	 *
	 * @return the type of this wc referenced file
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this wc referenced file.
	 *
	 * @param type the type of this wc referenced file
	 */
	public void setType(String type);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.liferay.dl.cleaner.model.WcReferencedFile wcReferencedFile);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.dl.cleaner.model.WcReferencedFile> toCacheModel();

	@Override
	public com.liferay.dl.cleaner.model.WcReferencedFile toEscapedModel();

	@Override
	public com.liferay.dl.cleaner.model.WcReferencedFile toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}