/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.dl.cleaner.model.impl;

import com.liferay.dl.cleaner.model.UnusedFile;
import com.liferay.dl.cleaner.service.UnusedFileLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the UnusedFile service. Represents a row in the &quot;DlCleaner_UnusedFile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UnusedFileImpl}.
 * </p>
 *
 * @author guywandji
 * @see UnusedFileImpl
 * @see com.liferay.dl.cleaner.model.UnusedFile
 * @generated
 */
public abstract class UnusedFileBaseImpl extends UnusedFileModelImpl
	implements UnusedFile {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a unused file model instance should use the {@link UnusedFile} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			UnusedFileLocalServiceUtil.addUnusedFile(this);
		}
		else {
			UnusedFileLocalServiceUtil.updateUnusedFile(this);
		}
	}
}