/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.dl.cleaner.model.impl;

import com.liferay.dl.cleaner.model.WcReferencedFile;
import com.liferay.dl.cleaner.service.WcReferencedFileLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the WcReferencedFile service. Represents a row in the &quot;DlCleaner_WcReferencedFile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link WcReferencedFileImpl}.
 * </p>
 *
 * @author guywandji
 * @see WcReferencedFileImpl
 * @see com.liferay.dl.cleaner.model.WcReferencedFile
 * @generated
 */
public abstract class WcReferencedFileBaseImpl extends WcReferencedFileModelImpl
	implements WcReferencedFile {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a wc referenced file model instance should use the {@link WcReferencedFile} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			WcReferencedFileLocalServiceUtil.addWcReferencedFile(this);
		}
		else {
			WcReferencedFileLocalServiceUtil.updateWcReferencedFile(this);
		}
	}
}