/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.dl.cleaner.service.base;

import com.liferay.dl.cleaner.model.LostFile;
import com.liferay.dl.cleaner.service.LostFileService;
import com.liferay.dl.cleaner.service.persistence.LostFilePersistence;
import com.liferay.dl.cleaner.service.persistence.UnusedFilePersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.UserPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the lost file remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.dl.cleaner.service.impl.LostFileServiceImpl}.
 * </p>
 *
 * @author guywandji
 * @see com.liferay.dl.cleaner.service.impl.LostFileServiceImpl
 * @see com.liferay.dl.cleaner.service.LostFileServiceUtil
 * @generated
 */
public abstract class LostFileServiceBaseImpl extends BaseServiceImpl
	implements LostFileService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.liferay.dl.cleaner.service.LostFileServiceUtil} to access the lost file remote service.
	 */

	/**
	 * Returns the lost file local service.
	 *
	 * @return the lost file local service
	 */
	public com.liferay.dl.cleaner.service.LostFileLocalService getLostFileLocalService() {
		return lostFileLocalService;
	}

	/**
	 * Sets the lost file local service.
	 *
	 * @param lostFileLocalService the lost file local service
	 */
	public void setLostFileLocalService(
		com.liferay.dl.cleaner.service.LostFileLocalService lostFileLocalService) {
		this.lostFileLocalService = lostFileLocalService;
	}

	/**
	 * Returns the lost file remote service.
	 *
	 * @return the lost file remote service
	 */
	public com.liferay.dl.cleaner.service.LostFileService getLostFileService() {
		return lostFileService;
	}

	/**
	 * Sets the lost file remote service.
	 *
	 * @param lostFileService the lost file remote service
	 */
	public void setLostFileService(
		com.liferay.dl.cleaner.service.LostFileService lostFileService) {
		this.lostFileService = lostFileService;
	}

	/**
	 * Returns the lost file persistence.
	 *
	 * @return the lost file persistence
	 */
	public LostFilePersistence getLostFilePersistence() {
		return lostFilePersistence;
	}

	/**
	 * Sets the lost file persistence.
	 *
	 * @param lostFilePersistence the lost file persistence
	 */
	public void setLostFilePersistence(LostFilePersistence lostFilePersistence) {
		this.lostFilePersistence = lostFilePersistence;
	}

	/**
	 * Returns the unused file local service.
	 *
	 * @return the unused file local service
	 */
	public com.liferay.dl.cleaner.service.UnusedFileLocalService getUnusedFileLocalService() {
		return unusedFileLocalService;
	}

	/**
	 * Sets the unused file local service.
	 *
	 * @param unusedFileLocalService the unused file local service
	 */
	public void setUnusedFileLocalService(
		com.liferay.dl.cleaner.service.UnusedFileLocalService unusedFileLocalService) {
		this.unusedFileLocalService = unusedFileLocalService;
	}

	/**
	 * Returns the unused file remote service.
	 *
	 * @return the unused file remote service
	 */
	public com.liferay.dl.cleaner.service.UnusedFileService getUnusedFileService() {
		return unusedFileService;
	}

	/**
	 * Sets the unused file remote service.
	 *
	 * @param unusedFileService the unused file remote service
	 */
	public void setUnusedFileService(
		com.liferay.dl.cleaner.service.UnusedFileService unusedFileService) {
		this.unusedFileService = unusedFileService;
	}

	/**
	 * Returns the unused file persistence.
	 *
	 * @return the unused file persistence
	 */
	public UnusedFilePersistence getUnusedFilePersistence() {
		return unusedFilePersistence;
	}

	/**
	 * Sets the unused file persistence.
	 *
	 * @param unusedFilePersistence the unused file persistence
	 */
	public void setUnusedFilePersistence(
		UnusedFilePersistence unusedFilePersistence) {
		this.unusedFilePersistence = unusedFilePersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();
	}

	public void destroy() {
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return LostFile.class;
	}

	protected String getModelClassName() {
		return LostFile.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = lostFilePersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.liferay.dl.cleaner.service.LostFileLocalService.class)
	protected com.liferay.dl.cleaner.service.LostFileLocalService lostFileLocalService;
	@BeanReference(type = com.liferay.dl.cleaner.service.LostFileService.class)
	protected com.liferay.dl.cleaner.service.LostFileService lostFileService;
	@BeanReference(type = LostFilePersistence.class)
	protected LostFilePersistence lostFilePersistence;
	@BeanReference(type = com.liferay.dl.cleaner.service.UnusedFileLocalService.class)
	protected com.liferay.dl.cleaner.service.UnusedFileLocalService unusedFileLocalService;
	@BeanReference(type = com.liferay.dl.cleaner.service.UnusedFileService.class)
	protected com.liferay.dl.cleaner.service.UnusedFileService unusedFileService;
	@BeanReference(type = UnusedFilePersistence.class)
	protected UnusedFilePersistence unusedFilePersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private LostFileServiceClpInvoker _clpInvoker = new LostFileServiceClpInvoker();
}